---
- name: Configure Web Servers
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <h1>Welcome to {{ inventory_hostname }} - Powered by Ansible</h1>
          </html>

    - name: Allow HTTP through firewall
      ufw:
        rule: allow
        port: '80'
        proto: tcp
